language: node_js
node_js:
  - node
cache: yarn
branches:
  only:
    - master
    - develop
deploy:
  provider: npm
  email: 'IAN.MIDDLETON.SCL@GMAIL.COM'
  api_key:
    secure: aDxTtRz9sns/jIE94NAw8iN/fauR2XM/VO/tV1jt23/Jzosg2+ieM4QkNQ0PU10bXr5OeK8ZTxbrXL20h8GTayTw4Y4CuFq72VL9LoSzd5OPINZkGl7YbiNPoJNXk5Q7K6bbOJ2bqMGnE7B1gRGpj7ocUrqAMUybsOcjIB7onsn5NNe1dUax+An+F/YBHw4tobqNdMspwwuysc5GIKlfssMszvPvY7SXExLF6vIbop17PVu7Ag3uuyIpIT0x1gIqLs8Ophbb02hAAkNsIEo58puvKraTeY90MsMofDxxgU7dKKx+d4flYMuKyGm/dUpCP/1VvDlY7cQBiyZeQOeYk4sjxFsWSr5F96p0eZVq2eYY5u86MANplLISGo7G1wjKx/X6/oj5ziRYhWiSaj0GcmLmSfaJxYfZilOZ8CBMPmtrVtozYAql+0LouGlcf2uKAqU4l4xerG9glFhbFH6ugNfEulNzhTIL7TlV8ZfErXT/ML/ntSLBrbGozJKLOZdtTJ7+IarABcO8BYY+CR+sdluQQ00vUeqywrRHG5lzu945O5i0seuB7pwlHShVS/I/yaarFgDIuvLuWorWE0ysxHjANj97bvLRTBxR0gTl6/agMw41AJbVN9oHvfdlLHqeC1AuG5twKJOVUqulPd3Xx6crA7HTL5CTRUZNocSAT18=
  on:
    tags: true
