export const DRIVER_UPDATE_SECTION = 'DRIVER_UPDATE_SECTION';
export const DRIVER_INSERT_ONE = 'DRIVER_INSERT_ONE';
export const DRIVER_INSERT_MANY = 'DRIVER_INSERT_MANY';
export const DRIVER_UPDATE_ONE = 'DRIVER_UPDATE_ONE';
export const DRIVER_UPDATE_MANY = 'DRIVER_UPDATE_MANY';
export const DRIVER_DELETE_ONE = 'DRIVER_DELETE_ONE';
export const DRIVER_DELETE_MANY = 'DRIVER_DELETE_MANY';
